name: flutter_issues
version: 1.0.0+1
publish_to: none
description: List of Issues in Flutter Github Repository
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: 4.6.5
  logger: ^2.0.2
  shimmer: ^3.0.0
  intl: ^0.18.1
  textfield_tags: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter: 
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21

